stages:
  - build
  - test
  - deploy

image: docker
services:
  - docker:dind

# BASE JOBS
.docker-login:
  before_script:
    - docker login registry.gitlab.com -u ${USERNAME} -p ${SALINE_TOKEN}
  variables:
    URL_GIT: registry.gitlab.com/arkhayds/saline-web3-academy/

.build-job:
  stage: build
  before_script:
    - apk add --no-cache --upgrade bash

.test-job:
  stage: test
  variables: 
    MAIN_APP: cd

.deploy-job:
  stage: deploy

# BUILD
build-nginx-container:
  extends: 
    - .build-job
  except:
    - merge_requests
  variables:
    URL_GIT: registry.gitlab.com/arkhayds/saline-web3-academy/
  script:
    - docker login registry.gitlab.com -u ${USERNAME} -p ${SALINE_TOKEN}
    - docker build -t ${URL_GIT}nginx-${CI_COMMIT_REF_NAME} .
    - docker push ${URL_GIT}nginx-${CI_COMMIT_REF_NAME}

# TEST
test-nginx-container:
  extends: 
    - .docker-login
    - .test-job
  except:
    - merge_requests
  script:
    - echo "The current branch is ${CI_COMMIT_REF_NAME}"
    - echo "------------------Test Nginx-----------------------------"
    - docker pull ${URL_GIT}nginx-${CI_COMMIT_REF_NAME}
    - echo "------------------Success Container registry work-------------------"

# DEPLOY
deploy-nginx-container:
  extends: 
    - .docker-login
    - .deploy-job
  except:
    - merge_requests
  script:
    - docker pull ${URL_GIT}nginx-${CI_COMMIT_REF_NAME}
    - docker stop nginx-${CI_COMMIT_REF_NAME}
    - docker rm nginx-${CI_COMMIT_REF_NAME}
    - docker run -d --name nginx-${CI_COMMIT_REF_NAME} -p 80:80 ${URL_GIT}nginx-${CI_COMMIT_REF_NAME}