stages:
  - build
  - test
  - deploy
  - deploy-merge
  - after_merge

image: docker
services:
  - docker:dind

# BASE JOBS
.build-job:
  stage: build
  before_script:
    - apk add --no-cache docker-compose ; apk add --no-cache --upgrade bash
  variables:
    CMD_DOCKER:  docker compose up -d

.test-job:
  stage: test
  variables: 
    MAIN_APP: cd

.deploy-job:
  stage: deploy

# BUILD
build-code-all:
  extends: .build-job
  except:
    - merge_requests
  variables:
    URL_GIT: registry.gitlab.com/ArkhayDs/saline-web3-academy/
  script:
    - docker compose up -d 
    - docker ps -a
    - docker login registry.gitlab.com -u ${USERNAME} -p ${SALINE_TOKEN} 
    - docker tag test-ci-cd-express ${URL_GIT}express-${CI_COMMIT_REF_NAME}
    - docker build -t ${URL_GIT}express-${CI_COMMIT_REF_NAME} backend
    - docker push ${URL_GIT}express-${CI_COMMIT_REF_NAME}
    - docker tag test-ci-cd-remix ${URL_GIT}remix-${CI_COMMIT_REF_NAME}
    - docker build -t ${URL_GIT}remix-${CI_COMMIT_REF_NAME} frontend
    - docker push ${URL_GIT}remix-${CI_COMMIT_REF_NAME}

# TEST
test-code-all:
  extends: .test-job
  except:
    - merge_requests
  variables:
    URL_GIT: registry.gitlab.com/ArkhayDs/saline-web3-academy/
  script:
    - echo "The current branch is ${CI_COMMIT_REF_NAME}"
    - echo "------------------Test Express-----------------------------"
    - docker pull ${URL_GIT}express-${CI_COMMIT_REF_NAME}
    - echo "------------------Test Remix-----------------------------"
    - docker pull ${URL_GIT}remix-${CI_COMMIT_REF_NAME}
    - echo "------------------Success Container registry work-------------------"

# MERGE ENVIRONMENTS
merge:
  stage: deploy-merge
  script:
    - docker compose up -d 
    - docker ps -a
    - docker login registry.gitlab.com -u ${USERNAME} -p ${SALINE_TOKEN} 
    - echo "This job runs in merge request pipelines"
    - if [ "$CI_COMMIT_REF_NAME" = "preprod" ]; then
    - docker tag test-ci-cd-express ${URL_GIT}express-main
    - docker build -t ${URL_GIT}express-main backend
    - docker push ${URL_GIT}express-main
    - docker tag test-ci-cd-remix ${URL_GIT}remix-main
    - docker build -t ${URL_GIT}remix-main frontend
    - docker push ${URL_GIT}remix-main
    - fi
    - if [ "$CI_COMMIT_REF_NAME" = "dev" ]; then
    - docker tag test-ci-cd-express ${URL_GIT}express-preprod
    - docker build -t ${URL_GIT}express-preprod backend
    - docker push ${URL_GIT}express-preprod
    - docker tag test-ci-cd-remix ${URL_GIT}remix-preprod
    - docker build -t ${URL_GIT}remix-preprod frontend
    - docker push ${URL_GIT}remix-preprod
    - fi
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'