version: '3.8'

services:
  express:
    restart: always
    build:
      context: ./backend
      dockerfile: ../docker/nodejs/Dockerfile
    container_name: saline_express
    ports: ['3000:3000']
  remix:
    restart: always
    build:
      context: ./frontend
      dockerfile: ../docker/remix/Dockerfile
    container_name: saline_remix
    ports: ['3001:3001']