version: '3.8'

services:
  express:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: saline_express
    ports: ['3000:3000']
  remix:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: saline_remix
    ports: ['3001:3001']
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: saline_db
    ports: ['3006:3006']