version: '3.8'

services:
  express:
    build:
      target: ${ENV_TARGET}
    command: npm run start:dev
    volumes: ['./backend:/var/www/salinebackend','/var/www/salinebackend/node_modules/']
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  remix:
    build:
      target: ${ENV_TARGET}
    command: npm run dev
    volumes: ['./frontend:/var/www/salinefrontend','/var/www/salinefrontend/node_modules/']
    environment:
      NODE_ENV: development