version: '3.8'

services:
  express:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: saline_express
    environment:
      - NODE_ENV=${ENV_TARGET} 
    volumes:
      - ./backend:/var/www/salinebackend
      - /var/www/salinebackend/node_modules
    command: npm run start:dev
    ports: ['3000:3000']

  remix:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: saline_remix
    command: npm run build && npm run serve
    ports: ['3001:3001','8002:8002']

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'saline_db'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    container_name: saline_database
    ports: ['3306:3306']