version: '3.8'

services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports: ['80:80', '403:403', '3010:3010', '3011:3011',  '3021:3021', '3020:3020']
