version: '3.8'

services:
  express:
    build:
      target: ${ENV_TARGET}
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    
  remix:
    build:
      target: ${ENV_TARGET}
    command: npm run dev
    environment:
      NODE_ENV: development