version: '3.8'

services:
  express:
    command: npm run start:dev
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/var/www/salinebackend
      - /var/www/salinebackend/node_modules

  db:
    platform: ${PLATFORM}
    
  remix:
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/var/www/salinefrontend
      - /var/www/salinefrontend/node_modules